spring:
#  profiles:
#    active: prod
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.231.63:3306/nest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  freemarker:
    cache: true
    settings:
      number_format: 0.######
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 49.234.231.63
    database: 1

  mail:
    port: 465
    host: smtp.ym.163.com
    username: xxxx@fengyunxiao.cn
    password: password
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: cn.fengyunxiao.nest.entity
  configuration:
    map-underscore-to-camel-case: false

# 用到 ssl 可以根据自己的配置
#server:
#  port: 443
#  ssl:
#    key-store: classpath:www.fengyunxiao.cn.jks
#    key-store-password: love13625
#    key-store-type: JKS
#    key-alias: 1
#  compression:
#    enabled: true
#    min-response-size: 512
#  max-http-header-size: 102400

logging:
  level:
    root: info
